apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: rahulltelkarboardapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rahulltelkarboardapp 
    spec:
      containers:
        - name: rahulltelkarboardapp 
          image: rahulimageregistry.azurecr.io/rahulltelkarboardapp
          ports:
          - containerPort: 8080