apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: rahul
  namespace: default
spec:
  replicas: 1
  selector:
     matchLabels: 
             app: rahulltelkarboard
  template:
    metadata:
      labels:
        app: rahulltelkarboard 
    spec:
      containers:
        - name: rahulltelkarboard 
          image: rahulimageregistry.azurecr.io/rahulltelkarboard
          ports:
          - containerPort: 8080

