apiVersion: v1
kind: Service
metadata:
    name: sample-app
    namespace :default
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http 
    selector:
        app: rahulltelkarboard
        
        
